name = "DSAModels"
uuid = "c94b82ce-bc6a-4c64-9fc0-cb2d7d683713"
authors = ["LudwigBoess <lboess@usm.lmu.de>"]
version = "0.1.0"

[deps]
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
SnoopPrecompile = "1"
julia = ">=1.8"
