name = "DSAModels"
uuid = "c94b82ce-bc6a-4c64-9fc0-cb2d7d683713"
authors = ["LudwigBoess <lboess@usm.lmu.de>"]
version = "1.0.0"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
PrecompileTools = "1"
julia = "1.6"
