name = "DSAModels"
uuid = "c94b82ce-bc6a-4c64-9fc0-cb2d7d683713"
authors = ["LudwigBoess <lboess@usm.lmu.de>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
