name: Deploy documentation

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  docdeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: registry_add
        run: julia -e 'using Pkg; pkg"registry add General https://github.com/LudwigBoess/LMBRegistry.git"'
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ""
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          DOCUMENTER_KEY: ${{ secrets.JLPKGBUTLER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
